[package]
name = "gstreamer_rs_qt_player"
version = "0.1.0"
build = "build.rs"
links = "gstreamer_rs_qt_player"

[dependencies]
libc = "*"
gstreamer = "0.15.5"
glib = "0.9.3"
gobject-sys = "0.9.1"
glib-sys = "0.9.1"
gstreamer-sys = "0.8.1"

[build-dependencies]
rust_qt_binding_generator = "0.3.5"
